// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RSOTransactionMicroServiceAPI.Models;

public partial class Transaction
{
    public int ID { get; set; }

    public int SellerId { get; set; }

    public int BuyerId { get; set; }

    public int AdId { get; set; }

    public int? PriceActual { get; set; }

    public DateTime DateTime { get; set; }
}